---
- hosts: all
  vars:
    install_dir: "/opt/prometheus/node_exporter"
    node_exporter_version: "1.0.1"
    download_link: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    user: "prometheus"
    group: "prometheus"
    shell: "/sbin/nologin"
    log_dir: "/var/log/prometheus"
    uid: "1555"
    gid: "1555"

  tasks:

  - name: create directory
    file:
      dest: "{{ item }}"
      state: directory
      mode: 0755
      recurse: yes
    with_items:
      - "{{ install_dir }}"
      - "{{ log_dir  }}"

  - unarchive:
      src: "{{ download_link }}"
      dest: "{{ install_dir }}"
      remote_src: True

  - file:
      src: "{{ install_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64//node_exporter"
      dest: "{{ install_dir }}/node_exporter"
      state: link


  - name: add group
    group:
      name: "{{ group }}"
      state: present
      gid: "{{ gid }}"

  - name: add user
    user:
      name: "{{ user }}"
      group: "{{ group }}"
      uid: "{{ uid }}"

  - name: setup systemctl service
    template:
      src: templates/node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
    #when: (ansible_distribution_major_version == "7" and ansible_distribution == "CentOS")


  - name: setup init
    template:
      src: templates/node_exporter.init.j2
      dest: /etc/init.d/node_exporter
      mode: 0755
    when: ansible_distribution_major_version == "6" and ansible_distribution == "CentOS"


  - name: restart service
    service:
      name: node_exporter
      enabled: yes
      state: restarted




